### ISSUE TITLE
Note or error regarding needing device to be plugged into external power

### ISSUE THREAD

**Issue by kattni** [adafruit/PyLeap-iOS#17]
I had forgotten about this requirement, and spent the last half hour or so banging my head against it. There's no error popping up when trying to transfer to a board that is plugged into a computer. I looked through PyLeap, and I don't see a tutorial relating to PyLeap overall usage (not that I'm suggesting their should be, only that such a thing would make sense to include this note), or a standalone note anywhere about requiring the board to be externally powered.

I'm not sure how you would integrate it. There is an error being thrown by CircuitPython, evidently, when you try to transfer while plugged into your computer, so maybe instead of a separate note, have an error window pop up with the external power requirement if a transfer is attempted while plugged into a computer.

As well, you may already be aware of all of this and working on it. I figured it was worth an issue regardless.

**Comment by TrevKnows** [comment]
@kattni Hey -I've added an alert prompt to the transfer button. Now if the paired device is connected to a computer, a message will appear that says "Cannot write to device" and "Unplug from computer and use external battery source".

Custom alerts for iOS has changed. For some reason, the alert prompt only appears once after the error is found. 
I'll find a hack around this. The alert should pop up every time the user can not write to the Bluetooth device.

**This change will be in the next TF 1.1(5)**
