### ISSUE TITLE
Feature request: "global" Connect button

### ISSUE THREAD

**Issue by kattni** [adafruit/PyLeap-iOS#19]
I have a idea for a feature to add to Limor's suggestion to include a bar at the top that shows your pairing status, and is red when no device is shared, and green when your device is paired.

My suggestion is to include a "Connect" button in that red bar when no device is paired. So basically the red bar would say "No device paired." and have next to the text a "Connect" button, exactly like the one inside a project when no board is paired (or a different color if it clashes with red). 

The button would not be present on the green bar when a device is paired.

At the moment, the expectation seems to be that a user should click on a desired project, and then click Connect once viewing a project. This feels like it might be a bit obtuse for new users.

I know you're in the middle of making a bunch of UI changes, and some resolution to this may already be in progress. But, basically, overall, being taken immediately to the project list page leaves a lot of questions unanswered. I think with a few minor changes, we can make it a much clearer experience.

Please let me know if you need or want any more info!

**Comment by kattni** [comment]
Update: I included this suggestion on the mockup design in Zeplin.

**Comment by TrevKnows** [comment]
"global" Connect button added.
**Will be added in TestFlight 1.1(6)**
![IMG_9363](https://user-images.githubusercontent.com/6743263/166262254-7d956d8b-057e-473e-97eb-a860a9d87932.jpg)
![IMG_9364](https://user-images.githubusercontent.com/6743263/166262273-9544d99e-332d-4c35-9df6-8827be9c21cf.jpg)
