### ISSUE TITLE
About half the time clicking "Download" does not bring up "Transfer"

### ISSUE THREAD

**Issue by kattni** [adafruit/PyLeap-iOS#20]
About half the time, so approximately every other project, when I click "Download", the Download button blinks, and then remains the Download button. If I click Download again, it brings up the Transfer button.

I can't reproduce this too many more times, because I will have downloaded all of the projects, so they will all show only Transfer at that point.

@TrevKnows Is there any way to delete the downloaded data from PyLeap, so I can come at it again "fresh"? I googled it, and it doesn't seem to work in the way some apps do. If I delete the app entirely, and load it again from TestFlight, will that remove the data, or will the data be preserved behind the scenes? I can simply try it, but I figured I would ask first since you have worked with this a lot more than I have. Thanks!

**Comment by kattni** [comment]
This is still happening consistently. I have downloaded the last project, though, so I will need to delete the app to test it again.

**Comment by kattni** [comment]
Still happening a bit less than half the time. I'll click download, and wait, and nothing will happen. Click it again, and it will show the transfer button.

**Comment by TrevKnows** [comment]
I have a fix for this in TestFlight 1.1(5)

**Comment by kattni** [comment]
This seems to have been resolved! The first time I clicked Download, it appeared to still have the issue, but as the issue is gone on every other instance of pressing Download, I think I simply didn't tap it right the first time.
