### ISSUE TITLE
Last project in the progress list does not expand

### ISSUE THREAD

**Issue by kattni** [adafruit/PyLeap-iOS#21]
All of the projects in the project list, when tapped on, expand to reveal the project info and Learn Guide / Download (Transfer) buttons. 

The final project, Step Counter, does not expand when tapped.

**Comment by TrevKnows** [comment]
I've taken a look at the last expanding cell, and it seems to be expanding but is hidden below the ScrollView. If the user taps the expanding cell and scroll downward, you'd be able to see its contents.

This is still an issues to be resolved.
*Note to self*
Will need to adjust scrollView scroll height once button is pressed.
and add safe area insets.

![IMG_F0EC5C30B6A2-1](https://user-images.githubusercontent.com/6743263/164510285-f34af54a-438e-44ec-9280-73eb6e3eb13d.jpeg)

**Comment by TrevKnows** [comment]
This issue has been resolved. 
The fix will be added into TestFlight 1.1(6)
