### ISSUE TITLE
Altimiter project description incorrect

### ISSUE THREAD

**Issue by kattni** [adafruit/PyLeap-iOS#22]
The Altimeter project description is from the MP3 Playback project. This needs to be updated.

**Comment by TrevKnows** [comment]
PyLeap receives remote JSON data from this [Github Page](https://github.com/adafruit/pyleap.github.io).
The JSON data has been updated.

If the description is still incorrect, then the JSON data is being cached for offline use. I've added a quick fix that removes cached data that will be in the nexts PyLeap TestFlight ver. 1.1(3)

**Comment by TrevKnows** [comment]
@kattni I'm currently adding additional text to PyLeap's onboarding view and fixing typos. 
Changes will be made for TestFlight version 1.1(3)

**Comment by kattni** [comment]
This issue has been resolved.
