### ISSUE TITLE
Delay between tapping "Run it!" and the download starting

### ISSUE THREAD

**Issue by kattni** [adafruit/PyLeap-iOS#41]
Is the delay between tapping “Run it!” and the download starting intentional? Or is it a quirk of the programming? First one I thought it was doing the thing where I pressed “Download” and it wouldn’t show it downloading. This time I kept tapping on the first one, and it eventually loaded. Second time, I pressed and waited and realised it’s a delay. I think if it’s something we can address, it might be worth doing.

**Comment by TrevKnows** [comment]
@kattni Ok, just fixed the issue. Now when the user taps the "Run it!" button, the title will change to "Downloading" immediately. 

**This fix will be in 1.1(7)**

**Comment by kattni** [comment]
Resolved in beta 7!
