### ISSUE TITLE
Show alert when USB is connected

### ISSUE THREAD

**Issue by tannewt** [adafruit/PyLeap-iOS#55]
Double check that the app will prompt you to disconnect from USB when the app gets the error that the file system is read-only.

Maybe we should also include the boot.py snippet in an advanced option:

```python
import storage
storage.disable_usb_drive()
```

**Comment by TrevKnows** [comment]
Looks like the previous way of adding alert modifiers in SwiftUI has been deprecated. 
**This has been updated and added to TestFlight 1.1(8)**
