### ISSUE TITLE
Remove Spinner

### ISSUE THREAD

**Issue by tylerdcooper** [adafruit/PyLeap-iOS#57]
A total minor issue, but if we have a status indicator, we don't need a spinner because the snake acts as the spinner. See below. I also don't think we need the spinner below the download progress bar (unless you are concerned of there being a lockup there).

![Screenshot_052022_103437_AM](https://user-images.githubusercontent.com/1672997/169562735-139ea858-8998-47e8-a895-5706c7c5e169.jpg)

**Comment by tylerdcooper** [comment]
We could do something like this for the download progress bar so there is some movement during the download process: https://codepen.io/gustitammam/pen/RRXGdj

**Comment by TrevKnows** [comment]
@tylerdcooper I agree with removing the activity spinner in the reconnection screen. Seems a bit redundant. 
Activity spinner removed in this view for **TestFlight 1.1(8)**

I think it might be a good idea to keep the activity spinner underneath the download progress bar until I'm able to put together a Dynamic Progress Bar. In situations where large files are being transferred, the app doesn't illustrate to the user that something is happening, the progress bar remains static until the large file has been transferred.
