### ISSUE TITLE
Unable to connect over WiFi (Version 2.1.0 (5))

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/PyLeap-iOS#96]
hihi! I've been trying to use the WiFi connectivity with a Feather ESP32-S2 TFT. I've tried running CircuitPython 7.3 release and 8.0.0.beta-3. So far I haven't been able to get the app to see the board. The board is running a WiFi test script in CircuitPython that connects to my network and then prints the IP address to the REPL every 10 seconds. I've tried manually entering the IP address and it says IP address not found. Not sure if there is a different script I should be running before connecting or if there's a setting on my phone I should check.

**Comment by BlitzCityDIY** [comment]
update on this: switched to TestFlight PyLeap 2.1.0 (6) and am now able to connect to the app with the updated .env variables for SSID and SSID password. When I try to download any of the examples though it just spins. The farthest I've been able to get is about 75% on the progress bar. ESP32-S2 TFT is running CP 8.0.0-beta4 and is running on a lipo.

**Comment by TrevKnows** [comment]
Did any of the examples transfer over to the board?

**Comment by TrevKnows** [comment]
@BlitzCityDIY Looks like I've run into this issue with CP 8.0.0 beta 4 as well. PyLeap worked with previous CP 8 betas. I'll add this to CP issues. Thanks for testing!

**Comment by BlitzCityDIY** [comment]
@TrevKnows ah okay, thanks! i'll hold off then on testing the new testflight.

**Comment by BlitzCityDIY** [comment]
hihi @TrevKnows - tested with the new testflight. Unfortunately still can't transfer a project over WiFi. I'm able to connect but of note, after connecting if I press back in the app it says no device found. (screen recording below)

https://drive.google.com/file/d/10TFa_9GVKMmbzOvSOUD3zicVEsGiV2Pl/view

**Comment by BlitzCityDIY** [comment]
hihi @TrevKnows - good news, got files transferring over wifi. the web api password had gotten messed up in the .env file. was able to confirm by connecting through the browser. i was able to load all of the example esp32-s2 projects.
